apiVersion: v1
kind: Secret
metadata:
  name: {{ include "qasim.fullname" . }}-secret
  labels:
    {{- include "qasim.labels" . | nindent 4 }}
type: Opaque
data:
  chainSecretHex: {{ .Values.secret.chainSecretHex | b64enc | quote }}
