apiVersion: v1
kind: Service
metadata:
  name: {{ include "qasim.fullname" . }}
  labels:
    {{- include "qasim.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9801
      protocol: TCP
      name: http
  selector:
    {{- include "qasim.selectorLabels" . | nindent 4 }}
